export const homeObjOne = {
    countdownTimer: true,
    bootstrapTimer: false,
    lightBg: false,
    firstBlock: true,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: "Connect MetaMask to start",
    description: "Level up your gangster to earn $GANG on the Ξ Blockchain",
    headline: "The first Play-To-Earn gangster game on the Ξ Blockchain",
    lightText: true,
    topLine: "Blockgangsters.io",
    img: require('../../images/logo.svg').default,
    alt: 'Image',
    start: '',

};

export const homeObjTwo = {
    countdownTimer: false,
    bootstrapTimer: false,
    lightBg: true,
    primary: false,
    imgStart: 'start', // start with image or start with text
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel: "Connect MetaMask to start",
    description: "Security is our highest priority. As such, random-numbers will be generated by the gold standard called Chainlink VRF.",
    headline: "Real random numbers",
    lightText: false,
    topLine: "Blockgangsters.io",
    img: require('../../images/Chainlink_Logo_Blue.svg').default,
    alt: 'Image',
    start: 'true',

};

export const homeObjThree = {
    countdownTimer: false,
    bootstrapTimer: false,
    lightBg: false,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: "Connect MetaMask to start",
    description: "Two weeks of community testing will start from November 1 until November 16",
    headline: "Beta on Polygon Mumbai testnet starting soon!",
    lightText: true,
    topLine: "Blockgangsters.io",
    img: require('../../images/gangster.svg').default,
    alt: 'Image',
    start: '',

};

export const homeObjFour = {
    countdownTimer: false,
    bootstrapTimer: true,
    lightBg: true,
    primary: false,
    imgStart: '',
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel: "Connect MetaMask to start",
    description: "Be the first to join and bootstrap yourself until December 31, 2021. Bootstrapping will open on mainnet launch.",
    headline: "Mainnet launch November 16, 2021",
    lightText: false,
    topLine: "Blockgangsters.io",
    img: require('../../images/car.png').default,
    alt: 'Image',
    start: '',

};

