import styled from '@emotion/styled/macro';
import { CountdowndTimer } from '../../features/countdowntimer/CountdownTimer';
import { Colors } from '../../styles/theme/colors/Colors';
import { breakpoint } from '../../styles/theme/responsive/breakpoint';
import { FaTelegram, FaTwitter, FaDiscord } from 'react-icons/fa';
import React from 'react';
import { EthContext } from '../../App';
import { BootstrapCounter } from '../../features/bootstrapcounter/BootstrapCounter';

const Home = () => {


    const [, , , , , , , , , , , , , , , , , , bootstrapUsed] = React.useContext(EthContext);

    return (
        <StyledHome>
            <StyledPageSection>
                <StyledSectionPart>
                    <CountdowndTimer countdownDate={new Date('2021-11-15')} />
                    <StyledTimerText> Join us now on social media to get started right away! </StyledTimerText>
                    <StyledSocialIcons>
                        <StyledSocialIconLink href="https://discord.gg/j3JGYthB" target="_blank" aria-label="Discord">
                            <FaDiscord />
                        </StyledSocialIconLink>
                        <StyledSocialIconLink href="https://twitter.com/blockgangsters" target="_blank" aria-label="Twitter">
                            <FaTwitter />
                        </StyledSocialIconLink>
                        <StyledSocialIconLink href="https://t.me/joinchat/hIJ1FYLDul1jNGQ0" target="_blank" aria-label="Telegram">
                            <FaTelegram />
                        </StyledSocialIconLink>
                    </StyledSocialIcons>
                </StyledSectionPart>
                <StyledSectionPart>
                    <StyledImage src="/images/logo.svg" alt="logo" />
                </StyledSectionPart>
            </StyledPageSection>
            <StyledPageSection>
                <StyledSectionPart>
                    <StyledTopLine>Blockgangsters.io</StyledTopLine>
                    <StyledTitle>Real random numbers</StyledTitle>
                    <StyledSubtitle>Security is our highest priority. As such, random-numbers will be generated by the gold standard called Chainlink VRF.</StyledSubtitle>
                </StyledSectionPart>
                <StyledSectionPart>
                    <StyledImage src='/images/Chainlink_Logo_Blue.svg' />
                </StyledSectionPart>
            </StyledPageSection>
            <StyledPageSection>
                <StyledSectionPart>
                    <StyledTopLine>Blockgangsters.io</StyledTopLine>
                    <StyledTitle>Beta on Polygon Mumbai testnet starting soon!</StyledTitle>
                    <StyledSubtitle>Two weeks of community testing will start from November 1 until November 16</StyledSubtitle>
                </StyledSectionPart>
                <StyledSectionPart>
                    <StyledImage src='/images/gangster.svg' />
                </StyledSectionPart>
            </StyledPageSection>
            <StyledPageSection>
                <StyledSectionPart>
                    <StyledTopLine>Blockgangsters.io</StyledTopLine>
                    <StyledTitle>Mainnet launch November 16, 2021</StyledTitle>
                    <StyledSubtitle>Be the first to join and bootstrap yourself until December 31, 2021. Bootstrapping will open on mainnet launch.</StyledSubtitle>
                    <BootstrapCounter bootstrapUsed={bootstrapUsed} />
                </StyledSectionPart>
                <StyledSectionPart>
                    <StyledImage src='/images/car.png' />
                </StyledSectionPart>
            </StyledPageSection>
        </StyledHome>
    )
}

export default Home;

const StyledHome = styled.div`
::-webkit-scrollbar {
display: none;
}
`
const StyledPageSection = styled.div`

    display: flex;
    align-items: center;
    flex-direction: column;

    flex-wrap: wrap;
    color: ${Colors.White};
    background: ${Colors.DarkTransparant};
    padding: 16px 16px;
    
    ${breakpoint.m} {
        flex-direction: row;
        width: 80%;
        margin-left: 20%;
        padding: 60px 50px;
    }

    :nth-child(even) {
        background: ${Colors.LightTransparant};
        color: ${Colors.Black};
    }
`

const StyledSectionPart = styled.div`
    display: flex;
    flex-direction: column;
    
    ${breakpoint.l} {
        justify-content: center;
        width: 50%;
    }
`

const StyledTimerText = styled.div`
    color: white;
    font-size: 20px;
    text-align: center;
`;

const StyledSocialIcons = styled.div`
    display: flex;
    margin-top: 50px;
    justify-content: center;
    align-items: center;
`

const StyledSocialIconLink = styled.a`
    color: #fff;
    font-size: 24px;
    margin-left: 30px;
    margin-right: 30px;
`

const StyledImage = styled.img`
    width: 100%;
    height: 100%;

    ${breakpoint.l} {
        padding-left: 20px;
    }
`

const StyledTopLine = styled.div`
    font-size: 18px;
    line-height: 16px;
    letter-spacing: 1.4px;
    margin-bottom: 16px;
`;

const StyledTitle = styled.h1`
    margin-bottom: 24px;
    font-size: 48px;
    line-height: 1.1;
`

const StyledSubtitle = styled.p`
    margin-bottom: 35px;
    font-size: 18px;
    line-height: 24px;
`